databases:
  - name: micronot
    ipAllowList: []
    databaseName: micronot
    user: micronot_user

services:
  - type: web
    name: budget
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronot
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false